# SPDX-FileCopyrightText: © 2024 The "Whiteprints" contributors <whiteprints@pm.me>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Ignore everything.
**

# Except the following.

## Sources
!pyproject.toml
!uv.lock

## Wheel
!dist/*.whl
