# SPDX-FileCopyrightText: © 2024 Romain Brault <mail@romainbrault.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Ignore everything.
**

# Except the following.

## Sources
!src/
!.git/
!pyproject.toml
!hatch.toml
!hatch_build.py
!LICENSES
!README.md
!uv.lock

## Template
!template
!jinja_template
!copier.yml
