# SPDX-FileCopyrightText: © 2024 The "Whiteprints" contributors <whiteprints@pm.me>
#
# SPDX-License-Identifier: GPL-3.0-or-later

version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3"
  commands:
    - curl -LsSf https://astral.sh/uv/install.sh | sh
    - $HOME/.local/bin/uvx --from rust-just just build-documentation $READTHEDOCS_OUTPUT/html/
