# SPDX-FileCopyrightText: © 2024 Romain Brault <mail@romainbrault.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3"
  commands:
    - curl -LsSf https://astral.sh/uv/install.sh | sh
    - $HOME/.cargo/bin/uvx --with tox-uv tox run -e build-documentation -- --jobs auto --builder html --keep-going ./docs/ $READTHEDOCS_OUTPUT/html/
