# SPDX-FileCopyrightText: © 2024 Romain Brault <mail@romainbrault.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0
        flags:
          - unit
        paths:
          - "src"
          - "tests"
