# SPDX-FileCopyrightText: © 2024 The "Whiteprints" contributors <whiteprints@pm.me>
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: 📚 Bug report
description: Report a documentation issue or suggest an improvement
title: "docs: :books: "
labels:
  - ["documentation", "triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        # Thanks for taking the time to fill out this documentation issue report!

        Before submitting an issue, please make sure the issue hasn't been already addressed by searching through the existing and past [issues](https://github.com/whiteprints/whiteprints/issues).

        By submitting a new issue, you agree with this project's [Code of Conduct](https://github.com/whiteprints/whiteprints/blob/main/CODE_OF_CONDUCT.md).

        We are also happy to accept contributions from our users by means of [pull requests](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests) 🚀. For more details see [here](https://github.com/whiteprints/whiteprintst/blob/main/CONTRIBUTING.md).
  - type: checkboxes
    id: terms
    attributes:
      label: Before submittig a new issue...
      options:
        - label: I have already searched for relevant issues.
          required: true
        - label: I agree to follow this project's Code of Conduct.
          required: true
  - type: textarea
    attributes:
      label: The documentation issue
      description: |
        A clear and concise description of what content is an issue in the documentation. Please provide a link to the content if possible.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Suggest a potential alternative/fix
      description: |
        Tell us how we could improve the documentation in this regard.
  - type: markdown
    attributes:
      value: |
        Thanks for contributing 🎉!
